### ISSUE TITLE
Little issues when using [ on tab complet

### ISSUE THREAD

**Issue by CloudeLecaw** [TheClowner/ccRides-Support#12]
When using /rideadm reload [all] (ou copy pasted it from wiki for example^^) then you get this info in chat becuase a [ was used.
in console you see nothing
![Snag_ba4637e](https://user-images.githubusercontent.com/12080017/97092086-31419900-1641-11eb-8bac-17de76f5fabf.png)

**Comment by TheClowner** [comment]
Has been fixed in upcoming v1.5.4
