### ISSUE TITLE
ccRides API

### ISSUE THREAD

**Issue by stijnb1234** [TheClowner/ccRides-Support#19]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I would be great to have an API for this plugin. Things like controlling rides and events (ride start, ride stop, maybe even an event on-ride?) would be great.

**Describe alternatives you've considered**
-

**Additional context**
I want to use the API for my ActionFoto plugin (public plugin, available on my site), to take an on-ride photo. Therefor I need an event so that I can make that integration.

**Comment by TheClowner** [comment]
Version 1.8.0 includes an initial API release - including access to some ride controls as well as events

[Developer API Wiki Page](https://github.com/TheClowner/ccRides-Support/wiki/Developer-API)
