### ISSUE TITLE
Topspin

### ISSUE THREAD

**Issue by Coastercam** [TheClowner/ccRides-Support#27]
**Ride Name**
Top spin ride like talacon or ripsaw at alton towers

**Description of Motion**
https://www.youtube.com/watch?v=CLhXBGWVtnM

Not an easy way to describe it so YouTube link will help 

**Images & Video**
> https://www.youtube.com/watch?v=CLhXBGWVtnM
> (https://i.ytimg.com/vi/CLhXBGWVtnM/maxresdefault.jpg 
> (https://i.ytimg.com/vi/cg04u3t70do/maxresdefault.jpg)`
> https://www.hussrides.com/sites/default/files/gallery/top-spin-suspended-g4.jpg
> https://www.holdtightriders.co.uk/wp-content/uploads/2016/11/hussspin-1.jpg

**Comment by carltheraveyt** [comment]
#7 
Already listed

**Comment by TheClowner** [comment]
Added in v1.7.0
