### ISSUE TITLE
New Towers Sequence issue

### ISSUE THREAD

**Issue by CloudeLecaw** [TheClowner/ccRides-Support#29]
We have a problem with the sitting angle of the carts

The Sequence Nr.7 seems not to work, The Sequence should "reset" the sets to angle 0,
but they stay at angle 100%

> Sequence
> 7 | Tilt seats to 0% (Horizontal)
> 8 | Tilt seats to 100% (LEAN_ANGLE)
> 

Our Squence:
```
    - 8:60
  ...a bit up
---- a circle
a bit down
a bit up
---- a circle
a bit down
a little break
    - 7:60
```

Issue: The seats stay at 100% Angle =/

On the next turn of the ride they also start very often at angle 100%
so there seems to be a problem with reseting of the seat angle

**Comment by TheClowner** [comment]
This is fixed in v1.6.2 (releasing on spigot shortly)
