### ISSUE TITLE
Ride entities stay despawned after world load

### ISSUE THREAD

**Issue by WakkaFlocka239** [TheClowner/ccRides-Support#31]
Server Version: Paper version git-Paper-613 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
ccRides Version: 1.6.2
Java Version: 1.8.0_282

**Describe the bug/Issue**
> A clear and concise description of what the bug is.
Ride entities don't respawn when the world loads.

Our server loads and unloads worlds depending on if they are being used or not.
Related code: https://paste.bnn.gg/fodew.java

**Expected behavior**
> A clear and concise description of what you expected to happen.
Ride entities to be spawned upon world/chunk load

**Screenshots/Video**
> If applicable, add screenshots/video to help explain your problem.

**Logs/Errors/Configs**
> Please include relevant Logs and configuration files.
Config: https://paste.bnn.gg/yaxay.yml

My current solution to this is reloading each ride in the world via console, after a player loads the world

**Comment by TheClowner** [comment]
Could you possibly turn on the `Debug.chunkLoad` option in your config and share your full server log when a world loads in?
(Sorry, it might be a bit spammy on your console.)

Also, unrelated note, but since you are running 1.16.5 `forceUpdateLocations` should not be needed, as it's only a workaround for the older bukkit api (ie. 1.12 or older). It'll just be adding unnecessary work for your server every tick.

**Comment by WakkaFlocka239** [comment]
Probably way more than you need, but I included it all until it stopped. (12,772 lines)
[ccRides Debug.txt](https://github.com/TheClowner/ccRides-Support/files/6381201/ccRides.Debug.txt)

And as for `forceUpdateLocations`, I had only enabled it to see if it fixed my issue, I turned it off as soon as I saw it helped none

**Comment by TheClowner** [comment]
Okay, it looks like an old bug has resurfaced where the server isn't calculating distances correctly. If you set `Entities.chunkDistanceCheck` to false it should resolve your issue (but may have a slight performance hit). 

I will look into the cause of it and try to fix it properly, the above solution is a workaround for now.

**Comment by TheClowner** [comment]
This should be resolved in `v1.6.3`
https://www.spigotmc.org/resources/ccrides-%C2%BB-working-theme-park-flat-rides-%C2%BB-1-8-x-to-1-16-x-%C2%BB.80364/update?update=400276

Please could you test with `Entities.chunkDistanceCheck` set `true` and confirm if it is fixed?

**Comment by WakkaFlocka239** [comment]
`Entities.chunkDistanceCheck` is `true`, updated the plugin, and disabled my own workaround.
`v1.6.3` fixes the issue. 👍
