### ISSUE TITLE
Ferriswheel rotation direction

### ISSUE THREAD

**Issue by WakkaFlocka239** [TheClowner/ccRides-Support#32]
**Describe the feature you'd like with as much detail as possible**
Ability to change the rotation direction of the ferriswheel

My current ferriswheel rotating backwards: https://i.imgur.com/aI41UJG.gif

I did think about rotating the model iteself, however when using the custom model option, the player cannot rotate a full 360 degrees like in a minecart, so it looks kinda odd when its rotated. Look at the gifs for a better understanding of what I mean.

_Player rotation in a minecart:_
https://i.imgur.com/TXEWsT8.gif

_Player rotation on a custom item model:_
https://i.imgur.com/dXIliKp.gif

**Comment by TheClowner** [comment]
Added `INVERT_ROTATION` option to the Ferris wheel in v1.6.6
