### ISSUE TITLE
Ride entities duplicating

### ISSUE THREAD

**Issue by WakkaFlocka239** [TheClowner/ccRides-Support#33]
Server Version: Paper version git-Paper-613 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
ccRides Version: 1.6.3
Java Version: 1.8.0_282

**Describe the bug/Issue**
Ride entities are duplicating
The entities are not being removed on chunk unload, and on chunk load new ones are being spawned on top of the old ones

**Screenshots/Video**
<img src=https://i.imgur.com/S4N6PHQ.png>
<img src=https://i.imgur.com/FEBe2H6.png>

**Logs/Errors/Configs**
Config: https://paste.bnn.gg/reveb.yml

**Comment by TheClowner** [comment]
Guess I forgot to apply the fix to distance checking to unloading as well as the chunk load. 
Fixed in v1.6.4

https://www.spigotmc.org/resources/ccrides-%C2%BB-working-theme-park-flat-rides-%C2%BB-1-8-x-to-1-16-x-%C2%BB.80364/update?update=400589
