### ISSUE TITLE
Teleport player somewhere when join queue

### ISSUE THREAD

**Issue by ImFound** [TheClowner/ccRides-Support#37]
Hello! I ask if it is possible to do that when the player enters the queue, he drops it somewhere, also to make the game more realistic. Obviously the flag will not be mandatory but optional. For example, "QUEUE_ENTER_LOCATION" is added in the settings.
I hope I explained myself.

Sincerely,
ImFound.

**Comment by TheClowner** [comment]
`QUEUE_TELEPORT` and `QUEUE_LOCATION` options have been added in version 1.6.7 for all rides.
