### ISSUE TITLE
Topspin - Rotation editing / Shortening arms

### ISSUE THREAD

**Issue by Tyfcho** [TheClowner/ccRides-Support#40]
**Describe the feature you'd like with as much detail as possible**
Make it so that we are able to change the block to be rotated from.

**Second feature**
Adding the possibility of changing the length of the arms without making the arms look taller than a certain amount of blocks.

**Comment by TheClowner** [comment]
Added `SHORT_ARMS` setting for TopSpin in 1.7.3, when set to true, the visual arms will be the exact length of `ARM_RADIUS`

If this doesn't do what you need, I could possibly add an option to set the distance the arm extends beyond the centre of rotation. But this was quick and easy to implement.
