### ISSUE TITLE
SmoothCoasters comptability

### ISSUE THREAD

**Issue by PanetiX** [TheClowner/ccRides-Support#42]
Hello,
would be great that ccRides will be compatible with SmoothCoasters Mod :)
https://www.curseforge.com/minecraft/mc-mods/smoothcoasters

This will significantly improve the experience of players when they are on a ride.

**Comment by PanetiX** [comment]
Hey, any updates for this? Here is an API for this ... 
https://github.com/56738/SmoothCoastersAPI

**Comment by TheClowner** [comment]
This is a duplicate of https://github.com/TheClowner/ccRides-Support/issues/24
