### ISSUE TITLE
[BUG] Ride will start message and trigger by joining already running ride

### ISSUE THREAD

**Issue by JaHollTV** [TheClowner/ccRides-Support#45]
When you join a running ride (if the option is enabled of cause) then you get the message 

"The ride will start in X seconds"
(X is the configured start time) 

and sometimes get kicked out of the ride.

**Comment by TheClowner** [comment]
This has been fixed in ccRides v1.7.9
https://www.spigotmc.org/resources/ccrides-%C2%BB-working-theme-park-flat-rides-%C2%BB-1-8-to-1-19-%C2%BB.80364/update?update=476458
