### ISSUE TITLE
1.19.2 - Causes much more performance draw

### ISSUE THREAD

**Issue by ItzSkyy** [TheClowner/ccRides-Support#47]
Server Version: 1.19.2
ccRides Version: 1.7.8
Java Version: 17

**Describe the bug/Issue**
> CCrides pulls near 20% of entire performance from the servers resources on world when nothing is even operating. no forceloading chunks, etc

**Expected behavior**
> Unsure but it sucks up alot of power. I do have the playermoveevent disabled too which made it worse

**Screenshots/Video**
> N/A

**Logs/Errors/Configs**
> N/A

**Comment by TheClowner** [comment]
I'm going to need some more information from you in order to look into this:

- Please add all your ccRides config files.
- Please add a timings report (use `/timings on`, wait a few minutes, then `/timings paste` and send the link)

**Comment by TheClowner** [comment]
This appears to be related to a paper bug which I have reported https://github.com/PaperMC/Paper/issues/8448
Enabling the `Rides.Operation.forceLoadChunks` option in ccRides config.yml reduces the lag impact and should prevent entities duplicating - until there is a proper fix.

**Comment by TheClowner** [comment]
Also going to close this as it is duplicated by https://github.com/TheClowner/ccRides-Support/issues/49
