### ISSUE TITLE
New Paper 1.19.2 Builds - Lag / Entity Duplication issue

### ISSUE THREAD

**Issue by CloudeLecaw** [TheClowner/ccRides-Support#49]
**Server and ccRides Version**

Plugin Informationen: ccRides Version: 1.7.8
Author(en): TheClowner, N1ghthauq
Status: Enabled
SofteAbhaenigkeit: Vault, PlaceholderAPI, ClearLag
This server is running Paper version git-Paper-199 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 77a50b9)
You are 1 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-196 (MC: 1.19.2)
Javaversion: 17.0.2+8-Ubuntu-118(04)

**Describe the bug/Issue**
When Rides are enabled (they dont need to run, just be enabled) after some hours, specialy when you got a lot  of rides, the rides start creating a big big tps lose + hoorobile drop of fps. We went down to 13 tps with a just 2 fps (well not best graficcard but normaly its 60 fps)
when the plugin is unloaded the tps went straight back to 20 and the fps back to 60.
when reloading the plugin with enabled rides all looks normal at first. after some hours the issue repeats.

For now we  added scheduler that unloads and loads the plugin every 60 minutes in the background, but this is not really a good solution ;/

note: since 1.19.2 Build 174 paper added their own chunkmanagment (spigot does not have it). A lot of plugins had issues with it. maybe this is a issue here too..

**Comment by TheClowner** [comment]
It'd be super helpful if you were able to send a timings report from when the lag happens - 

> `/timings on` - wait a few minutes `/timings paste`

I haven't had a chance to test against paper's new chunks system - I'll update my test server later today and see if this is something I can fix - it could be an issue with paper itself though depending on what's causing it.

**Comment by TheClowner** [comment]
This appears to be related to a paper bug which I have reported https://github.com/PaperMC/Paper/issues/8448

Enabling the `Rides.Operation.forceLoadChunks` option in ccRides config.yml reduces the lag impact and should prevent entities duplicating - until there is a proper fix.
