### ISSUE TITLE
More permissions and commands

### ISSUE THREAD

**Issue by veldik** [TheClowner/ccRides-Support#5]
# More permissions and commands
## Add more permissions:
- ccrides.use.[rideName] - Permission for specify ride
- ccrides.use.* - Permission for all rides
- ccride.discount.[percentage] - percentage of discount by permissions
## Command:
- /ccride [rideName] - Command already exists, but with tab don't recommends names of rides
- /ccride [rideName] all - Admin command for ride join all players on server 
- /ccride [rideName] [nick] - Admin command for ride join ride another player

**Comment by TheClowner** [comment]
I am adding per ride permissions `ccrides.ride.[rideName]`
and force join commands in v1.2.1, as well as a couple other extra commands.
