### ISSUE TITLE
ccRides API bug

### ISSUE THREAD

**Issue by GabryOsas** [TheClowner/ccRides-Support#51]
**Server and ccRides Version**
Server Version:
1.16.5 Paper
ccRides Version:
1.8.0
Java Version: 
16

**Describe the bug/Issue**
> When the ride is started via the API provided by ccRides, the countdown if already activated will not disappear but will remain until its end

**Expected behavior**
> In theory, in my opinion, if the carousel is started via the API but its countdown has already been activated previously it should disappear because it actually makes no sense for the countdown to continue even if the carousel is already activated.

**Screenshots/Video**
> https://www.youtube.com/watch?v=I6Oou94hgOA

**Logs/Errors/Configs**
> There is no errors about it.

**Comment by TheClowner** [comment]
This is fixed in v1.8.1
