### ISSUE TITLE
Feature - Player in cart "whirls" arround with carts - PLS add PITCH and YAW of the Ride - Realistic Riding!

### ISSUE THREAD

**Issue by CloudeLecaw** [TheClowner/ccRides-Support#6]
no matter if the teecup are or the tower or a spin. when its wirling arround and or the car moves in a circle the player pitch and yaw did not get fixed to the one of the minecart

if pitch and yaw of the player would move with the minecart this would look more then crazzy realistic

at the moment pitch and yaw and so the angle at the moment is fixed to the position where the player is
this looks a bit unrealistic specially when the minecart moves or whils arround under your feed or get an other angle like at the top of the tower or at the chain-charusells

**Comment by CloudeLecaw** [comment]
Would be nice if Pitch and Yaw could be added to rides

**Comment by TheClowner** [comment]
As of ccRides v1.7.6, this is supported with the SmoothCoasters client mod.

**Comment by CloudeLecaw** [comment]
A mod is paper/spigot?
So how can i use it on a ccride ?
