### ISSUE TITLE
Dismounting a minecart created Event?

### ISSUE THREAD

**Issue by CloudeLecaw** [TheClowner/ccRides-Support#8]
when we dismount a lore that is no CCride we get an information in the console about dismounting.
Interesting is that this event got pasted 5 to 8 times each time
We hope you can fix this soon :-) 
A normal minecart that is no ccride should not dtrigger a ccride event :3

```
> [15:55:25] [Server thread/INFO]: [ccRides] Dismount Event
> [15:55:25] [Server thread/INFO]: [ccRides] Dismount Event
> [15:55:25] [Server thread/INFO]: [ccRides] Dismount Event
> [15:55:25] [Server thread/INFO]: [ccRides] Dismount Event
> [15:55:25] [Server thread/INFO]: [ccRides] Dismount Event
> [15:55:25] [Server thread/INFO]: [ccRides] Dismount Event
> [15:55:25] [Server thread/INFO]: [ccRides] Dismount Event
> [15:55:25] [Server thread/INFO]: [ccRides] Dismount Event
```

**Comment by TheClowner** [comment]
That appears to be some debug code I might've left in, my bad. It isn't actually doing anything on those events, just logging that it happened. Will be fixed in 1.3.7
